# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genio.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'genio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgenio.proto\"#\n\x13\x43umprimentarRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"%\n\x11\x43umprimentarReply\x12\x10\n\x08mensagem\x18\x01 \x01(\t2K\n\x13\x43umprimentarService\x12\x34\n\x08\x64izerOla\x12\x14.CumprimentarRequest\x1a\x12.CumprimentarReplyB!\n\x0c\x63umprimentarB\x11\x43umprimentarProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014cumprimentarB\021CumprimentarProto'
  _globals['_CUMPRIMENTARREQUEST']._serialized_start=15
  _globals['_CUMPRIMENTARREQUEST']._serialized_end=50
  _globals['_CUMPRIMENTARREPLY']._serialized_start=52
  _globals['_CUMPRIMENTARREPLY']._serialized_end=89
  _globals['_CUMPRIMENTARSERVICE']._serialized_start=91
  _globals['_CUMPRIMENTARSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
