# Generated by Django 5.1.7 on 2025-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
