# Generated by Django 5.1.7 on 2025-03-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atual', models.DateField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.musica')),
            ],
        ),
    ]
