# Generated by Django 5.2.4 on 2025-07-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_musicaatual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
