# Generated by Django 5.2.4 on 2025-07-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_musica_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='imagem',
        ),
    ]
