# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genio.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'genio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgenio.proto\"\x1c\n\x0cGenioRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x1e\n\nGenioReply\x12\x10\n\x08mensagem\x18\x01 \x01(\t26\n\x0cGenioService\x12&\n\x08\x64izerOla\x12\r.GenioRequest\x1a\x0b.GenioReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENIOREQUEST']._serialized_start=15
  _globals['_GENIOREQUEST']._serialized_end=43
  _globals['_GENIOREPLY']._serialized_start=45
  _globals['_GENIOREPLY']._serialized_end=75
  _globals['_GENIOSERVICE']._serialized_start=77
  _globals['_GENIOSERVICE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
